#pragma once
#include <memory>

class AST;
class ASTCompUnit;
class ASTTaskDef;
class ASTTaskParams;
class ASTInParamList;
class ASTOutParamList;
class ASTParamDecl;
class ASTTaskBody;
class ASTStateDecl;
class ASTNode;
class ASTComNode;
class ASTDecNode;
class ASTLeafNode;
class ASTSeqNode;
class ASTSelNode;
class ASTChildBlock;
class ASTRetryNode;
class ASTToutNode;
class ASTSkillCall;
class ASTTaskCall;
class ASTCheckStmt;
class ASTWaitStmt;
class ASTBindSec;
class ASTInBindings;
class ASTOutBindings;
class ASTInBinding;
class ASTOutBinding;
class ASTValue;
class ASTCondExp;
class ASTLOrExp;
class ASTLAndExp;
class ASTEqExp;
class ASTRelExp;
class ASTAddExp;
class ASTMulExp;
class ASTUnaryExp;
class ASTPrimaryExp;
class ASTLiteral;
class ASTRef;
class ASTDuration;
class ASTType;
class ASTBuiltinType;

using ASTSPtr = std::shared_ptr<AST>;
using ASTCompUnitSPtr = std::shared_ptr<ASTCompUnit>;
using ASTTaskDefSPtr = std::shared_ptr<ASTTaskDef>;
using ASTTaskParamsSPtr = std::shared_ptr<ASTTaskParams>;
using ASTTaskBodySPtr = std::shared_ptr<ASTTaskBody>;
using ASTInParamListSPtr = std::shared_ptr<ASTInParamList>;
using ASTOutParamListSPtr = std::shared_ptr<ASTOutParamList>;
using ASTParamDeclSPtr = std::shared_ptr<ASTParamDecl>;
using ASTStateDeclSPtr = std::shared_ptr<ASTStateDecl>;
using ASTNodeSPtr = std::shared_ptr<ASTNode>;
using ASTComNodeSPtr = std::shared_ptr<ASTComNode>;
using ASTDecNodeSPtr = std::shared_ptr<ASTDecNode>;
using ASTLeafNodeSPtr = std::shared_ptr<ASTLeafNode>;
using ASTSeqNodeSPtr = std::shared_ptr<ASTSeqNode>;
using ASTSelNodeSPtr = std::shared_ptr<ASTSelNode>;
using ASTChildBlockSPtr = std::shared_ptr<ASTChildBlock>;
using ASTRetryNodeSPtr = std::shared_ptr<ASTRetryNode>;
using ASTToutNodeSPtr = std::shared_ptr<ASTToutNode>;
using ASTSkillCallSPtr = std::shared_ptr<ASTSkillCall>;
using ASTTaskCallSPtr = std::shared_ptr<ASTTaskCall>;
using ASTCheckStmtSPtr = std::shared_ptr<ASTCheckStmt>;
using ASTWaitStmtSPtr = std::shared_ptr<ASTWaitStmt>;
using ASTBindSecSPtr = std::shared_ptr<ASTBindSec>;
using ASTInBindingsSPtr = std::shared_ptr<ASTInBindings>;
using ASTInBindingSPtr = std::shared_ptr<ASTInBinding>;
using ASTOutBindingsSPtr = std::shared_ptr<ASTOutBindings>;
using ASTOutBindingSPtr = std::shared_ptr<ASTOutBinding>;
using ASTValueSPtr = std::shared_ptr<ASTValue>;
using ASTCheckStmtSPtr = std::shared_ptr<ASTCheckStmt>;
using ASTCondExpSPtr = std::shared_ptr<ASTCondExp>;
using ASTLOrExpSPtr = std::shared_ptr<ASTLOrExp>;
using ASTLAndExpSPtr = std::shared_ptr<ASTLAndExp>;
using ASTEqExpSPtr = std::shared_ptr<ASTEqExp>;
using ASTRelExpSPtr = std::shared_ptr<ASTRelExp>;
using ASTAddExpSPtr = std::shared_ptr<ASTAddExp>;
using ASTMulExpSPtr = std::shared_ptr<ASTMulExp>;
using ASTUnaryExpSPtr = std::shared_ptr<ASTUnaryExp>;
using ASTPrimaryExpSPtr = std::shared_ptr<ASTPrimaryExp>;
using ASTWaitStmtSPtr = std::shared_ptr<ASTWaitStmt>;
using ASTLiteralSPtr = std::shared_ptr<ASTLiteral>;
using ASTRefSPtr = std::shared_ptr<ASTRef>;
using ASTDurationSPtr = std::shared_ptr<ASTDuration>;
using ASTTypeSPtr = std::shared_ptr<ASTType>;
using ASTBuiltinTypeSPtr = std::shared_ptr<ASTBuiltinType>;

class SynParser;
class ASTVisitor;